# Database Connection (Replaces DBConnection.java)
spring.datasource.url=jdbc:mysql://localhost:3306/wonderland_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tayyabarafique204@gmail.com
spring.mail.password=tyxybojewxnbxyxt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Server Port
server.port=8080
app.upload.dir=C:/Users/hp/OneDrive - Higher Education Commission/Desktop/uploads/
# Allow automatic restart on save
spring.devtools.restart.enabled=true